name: tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  badges: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^1.1.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  pedantic_mono: any
  retrofit_generator: ^2.1.0+1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
